import {
  TrainFront, Plane, Hotel, MapPin, Clock, Map, Luggage, Ticket,
  CloudSun, ChevronDown, ChevronRight, Armchair, Utensils, Camera,
  Footprints, Bath, Coffee, MountainSnow, Flame, Ship, Waves,
  Truck, Package, PackageCheck, Home, ExternalLink, CalendarDays,
  Sparkles, Check, CircleDot, Users, CreditCard, Tag, Info,
  Sunrise, Sunset, Sun, Moon,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  Train: TrainFront,
  Plane,
  Hotel,
  MapPin,
  Clock,
  Map,
  Luggage,
  Ticket,
  Cloud: CloudSun,
  Chevron: ChevronDown,
  ChevronRight,
  Armchair,
  Utensils,
  Camera,
  Footprints,
  Bath,
  Coffee,
  Mountain: MountainSnow,
  Flame,
  Ship,
  Waves,
  Truck,
  Package,
  PackageCheck,
  Home,
  ExternalLink,
  Calendar: CalendarDays,
  Sparkles,
  Check,
  CircleDot,
  Users,
  CreditCard,
  Tag,
  Info,
  Sunrise,
  Sunset,
  Sun,
  Moon,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? CircleDot;
}
